networks:
  app:

volumes:
  mysql_data:
servces:
  backend:
    container_name: backend_container
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8001"
    env_file:
      - backend/.env
    networks:
      - app
    command: bash -c "cd /app/backend && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./backend:/app/backend  # Sync local backend code
      - ./backend/static:/app/backend/static  # Sync local static files
    depends_on:
      - mysql_db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    container_name: frontend_container

  mysql_db:
    container_name: mysql_con_2
    image: mysql
    restart: always
    networks:
      - app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=edutech_newdb
      - MYSQL_USER=ajintha
      - MYSQL_PASSWORD=ajintha12345
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_con_2
    image: phpmyadmin
    restart: always
    networks:
      - app
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql_db