networks:
  app:

volumes:
  mysql_data:
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    expose:
      - "8001"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=edutech_newdb
      - MYSQL_USER=ajintha
      - MYSQL_PASSWORD=ajintha12345
    networks:
      - app
    depends_on:
      - mysql_db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    container_name: frontend_container

  mysql_db:
    container_name: mysql_con_2
    image: mysql
    restart: always
    networks:
      - app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=edutech_newdb
      - MYSQL_USER=ajintha
      - MYSQL_PASSWORD=ajintha12345
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_con_2
    image: phpmyadmin
    restart: always
    networks:
      - app
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql_db